max_width = 120
hard_tabs = false
tab_spaces = 4
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
fn_single_line = true
where_single_line = true
format_code_in_doc_comments = true
wrap_comments = true
